import { and, asc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { appointment, position } from "@scouthub/database";
import type { Appointment, AppointmentStatus, Position } from "@scouthub/domain";
import type { AppointmentRepository, AppointmentTransaction, PositionRepository, PositionTransaction } from "@scouthub/application";

type Db = Pick<ReturnType<typeof drizzle>, "select" | "insert" | "update">;
export function createPgPositionRepository(url: string): PositionRepository { return new PgPositionRepository(url); }
export function createPgAppointmentRepository(url: string): AppointmentRepository { return new PgAppointmentRepository(url); }
class PgPositionRepository implements PositionRepository { constructor(private readonly url: string) {} async transaction<T>(handler: (tx: PositionTransaction) => Promise<T>): Promise<T> { const pool = new pg.Pool({ connectionString: this.url, max: 1 }); try { return await drizzle(pool).transaction((db) => handler(new PositionTx(db))); } finally { await pool.end(); } } }
class PositionTx implements PositionTransaction { constructor(private readonly db: Db) {} async create(value: Position) { const [row] = await this.db.insert(position).values({ ...value, allowedScopeTypes: [...value.allowedScopeTypes] }).returning(); if (!row) throw new Error("Position insert returned no row"); return mapPosition(row); } async findById(tenantId: string, id: string) { const [row] = await this.db.select().from(position).where(and(eq(position.tenantId, tenantId), eq(position.id, id))).limit(1); return row ? mapPosition(row) : null; } async list(tenantId: string) { const rows = await this.db.select().from(position).where(eq(position.tenantId, tenantId)).orderBy(asc(position.title)); return rows.map(mapPosition); } async update(tenantId: string, id: string, patch: Partial<Position>) { const [row] = await this.db.update(position).set({ ...patch, updatedAt: new Date(), allowedScopeTypes: patch.allowedScopeTypes ? [...patch.allowedScopeTypes] : undefined }).where(and(eq(position.tenantId, tenantId), eq(position.id, id))).returning(); return row ? mapPosition(row) : null; } }
class PgAppointmentRepository implements AppointmentRepository { constructor(private readonly url: string) {} async transaction<T>(handler: (tx: AppointmentTransaction) => Promise<T>): Promise<T> { const pool = new pg.Pool({ connectionString: this.url, max: 1 }); try { return await drizzle(pool).transaction((db) => handler(new AppointmentTx(db))); } finally { await pool.end(); } } }
class AppointmentTx implements AppointmentTransaction { constructor(private readonly db: Db) {} async create(value: Appointment) { const [row] = await this.db.insert(appointment).values(value).returning(); if (!row) throw new Error("Appointment insert returned no row"); return mapAppointment(row); } async findById(tenantId: string, id: string) { const [row] = await this.db.select().from(appointment).where(and(eq(appointment.tenantId, tenantId), eq(appointment.id, id))).limit(1); return row ? mapAppointment(row) : null; } async list(tenantId: string, status?: AppointmentStatus) { const rows = await this.db.select().from(appointment).where(status ? and(eq(appointment.tenantId, tenantId), eq(appointment.status, status)) : eq(appointment.tenantId, tenantId)).orderBy(asc(appointment.startsAt), asc(appointment.id)); return rows.map(mapAppointment); } async update(tenantId: string, id: string, patch: Partial<Appointment>) { const [row] = await this.db.update(appointment).set({ ...patch, updatedAt: new Date() }).where(and(eq(appointment.tenantId, tenantId), eq(appointment.id, id))).returning(); return row ? mapAppointment(row) : null; } }
function mapPosition(row: typeof position.$inferSelect): Position { return { ...row, allowedScopeTypes: row.allowedScopeTypes as Position["allowedScopeTypes"] }; }
function mapAppointment(row: typeof appointment.$inferSelect): Appointment { return row; }
