export type ProjectStatus =
  | "DRAFT"
  | "READY_FOR_REVIEW"
  | "IN_REVIEW"
  | "CHANGES_REQUESTED"
  | "APPROVED_FOR_EXECUTION"
  | "IN_EXECUTION"
  | "EXECUTION_COMPLETED"
  | "FINAL_REVIEW"
  | "FINAL_CHANGES_REQUESTED"
  | "VALIDATED"
  | "READY_FOR_PUBLICATION"
  | "PUBLISHED"
  | "EXTERNAL_SUBMITTED"
  | "MONITORING"
  | "CLOSED"
  | "CANCELLED"
  | "REJECTED"
  | "ARCHIVED";

export const projectStatuses = [
  "DRAFT",
  "READY_FOR_REVIEW",
  "IN_REVIEW",
  "CHANGES_REQUESTED",
  "APPROVED_FOR_EXECUTION",
  "IN_EXECUTION",
  "EXECUTION_COMPLETED",
  "FINAL_REVIEW",
  "FINAL_CHANGES_REQUESTED",
  "VALIDATED",
  "READY_FOR_PUBLICATION",
  "PUBLISHED",
  "EXTERNAL_SUBMITTED",
  "MONITORING",
  "CLOSED",
  "CANCELLED",
  "REJECTED",
  "ARCHIVED"
] as const;
